# -*- coding: utf-8 -*-
"""Copy of Yolo_World_Webcam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBIP7T-wMoiSvRIIsAOGPBUpbT0vIXnV
"""

!pip install supervision
!pip install inference-gpu[yolo-world]
#!pip install inference-cpu[yolo-world]

import cv2
from tqdm import tqdm
import supervision as sv
from inference.models.yolo_world.yolo_world import YOLOWorld

model = YOLOWorld(model_id="yolo_world/l")

classes = ["person","dust","snow","debries","bird dropping","water"]
model.set_classes(classes)

results = model.infer("https://media.roboflow.com/inference/people-walking.jpg")

results

from IPython.display import display, Javascript, Image, clear_output
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import time

# Function to take a photo using a webcam in Colab
def take_photo(filename='photo.jpg', quality=0.5):
    js = Javascript('''
    async function takePhoto(quality) {
      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});
      video.srcObject = stream;
      await video.play();

      // Wait for a short time to allow the camera to adjust
      await new Promise(resolve => setTimeout(resolve, 500));

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
    display(js)
    data = eval_js(f'takePhoto({quality})')
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

# Initialize annotators
# Initialize annotators
BOUNDING_BOX_ANNOTATOR = sv.BoxAnnotator(thickness=2)
LABEL_ANNOTATOR = sv.LabelAnnotator(text_thickness=1, text_scale=0.5, text_color=sv.Color.BLACK)

try:
    while True:
        # Capture photo
        filename = take_photo()
        print(f'Saved to {filename}')

        # Load image for inference and annotation
        frame = cv2.imread(filename)
        results = model.infer(frame, confidence=0.002)
        detections = sv.Detections.from_inference(results).with_nms(threshold=0.8)

        # Annotate image
        annotated_frame = BOUNDING_BOX_ANNOTATOR.annotate(frame, detections)
        annotated_frame = LABEL_ANNOTATOR.annotate(annotated_frame, detections)

        # Save and display the annotated image
        annotated_filename = 'annotated_' + filename
        cv2.imwrite(annotated_filename, annotated_frame)

        # Clear previous output and display new image
        clear_output(wait=True)
        display(Image(annotated_filename))

        # Wait for a short period before taking the next photo
        #time.sleep(1)  # Adjust the sleep time as needed

except KeyboardInterrupt:
    print("Stopped the photo capture.")
except Exception as err:
    print(str(err))  # Error handling for webcam access